### PR TITLE
Tutorial Quest Additions

### PR DESCRIPTION
**Pull request by AstralSyntax**
Added the following quest from BetonQuest discord -
Bats Dungeon
Monster Hunter
Lumberjack

### CODE REVIEW

**Comment by seyfahni** [comment]
To keep files in this repository consistent, please add an empty line to every file.

**Comment by Wolf2323** [comment]
> To keep files in this repository consistent, please add an empty line to every file.

Maybe we should add an editor config configuration and a workflow checking for it

**Comment by Wolf2323** [comment]
We added editorconfig now, now your PR does not build anymore, as there are violsations

**Comment by Wolf2323** [comment]
Unfortunately this PR is now that long opened waiting for the file fixed to get done, that i now close this PR. Feel free to reopen it. when the work is done

**Pull request closed without merging**
